# Use postgres/example user/password credentials
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRESS_DB: postgres

