# Use postgres/example user/password credentials
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRESS_DB: postgres
      POSTGRES_HOST: postgres

  todo:
    build: .
    container_name: todo
    depends_on:
      - postgres
    restart: on-failure

    environment:
      DB_HOST: postgres
      DB_PORT: 5432:5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: mysecretpassword
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432
      PORT: 9000

    ports:
        - 9000:9000

  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./metrics/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"




